#playbook is a list of Plays
- name: PLAY-1
  hosts: localhost
  tasks:  
  - name: PLAY-1 and tASK-1
    anisble.builtin.debug:
      msg: "this msg is from play-1 & task 1"
    
- name: PLAY-2
  hosts: localhost
  tasks:
  - name: Play 2 and task 2 
    anisble.builtin.debug:
      msg: "this msg is from play 2 & task 2"