#playbook is a list of Plays
- name: Play 1
  hosts: localhost
  tasks:  
  - name: play 1 and task 1
    anisble.builtin.debug:
      msg: "this msg is from task 1"
    
- name: Play 2
  hosts: localhost
  tasks:
  - name: Play 2 and task 2 
    anisble.builtin.debug:
      msg: "this msg is from task 2"