#this is play level variables
- name: variables from play level
  hosts: localhost
  vars:
    student_name: "ADITYA KONADA"
    course: "Devops"
    duration: "110HR"
  tasks:
  - name: testing variables
    ansible.builtin.debug:
      msg: "I am {{ student_name }}, learning {{course}} and duration of course is {{duration}}"

#declaring variables in play level, using declared variables in task level. 