- name: variables learning
  hosts: localhost
  vars_files:
    variables1.yaml
  tasks:
  - name: variable from files
    ansible.builtin.debug:
      msg: "the student name is {{student_name}} studying course{{course}} of duration {{duration}}"
