- name: variables from inventory
  hosts: localhost
  tasks:
    - name: printing the variables from inventory
      ansible.builtin.debug:
        msg: "the name is {{student_name}} and studying {{course}} and duration is {{duration}}"