- name: learning conditions
  hosts: localhost
  become: yes
  tasks:
    - name: Id-ing roboshop
      ansible.builtin.command: id roboshop
      register: user_var #user_var is a variable 
      ignore_errors: true #ansible will not exit even if it gets error

    - name: printing register value of user_var
      ansible.builtin.debug:
        msg: "the user_var output is {{user_var}}"

    - name: print the exit status
      ansible.builtin.debug:
        msg: "the exit status is {{user_var.rc}}" #rc is exit status in .json

    - name: creating roboshop user using coditions
      ansible.builtin.user:
        name: roboshop
      when: user_var.rc != 0 #when is condition: 
    