- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print loops
    ansible.builtin.debug:
     name: "{{item.name}}"
     state: "{{item.loop}}" #item is default command
    loop:
      - {name: 'git' , state: 'present' } # item 
      - {name: 'mysql' , state: 'absent' }
      - {name: 'nginx' , state: 'present' }
      - {name: 'postfix' , state: 'absent' }

      # items in loops are given as list. 